# =============================================================================
# Ansible Inventory - Auto-generated by Terraform
# =============================================================================
# DO NOT EDIT MANUALLY - This file is regenerated on terraform apply
# =============================================================================

all:
  children:
    # Management/Monitoring infrastructure
    management:
      hosts:
        rcj-management:
          ansible_host: ${management_ip}
          private_ip: ${management_private_ip}
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3

    # Application servers (targets for monitoring agents)
    application_servers:
      hosts:
%{ for droplet in vpc_droplets ~}
%{ if droplet.name != "rcj-management" ~}
        ${droplet.name}:
          ansible_host: ${droplet.ipv4_address}
          private_ip: ${droplet.ipv4_address_private}
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
%{ endif ~}
%{ endfor ~}

  vars:
    # Management node connection info (for agent configs)
    prometheus_server: ${management_private_ip}
    loki_server: ${management_private_ip}
