# =============================================================================
# Ansible Inventory - Auto-generated by Terraform
# =============================================================================
# DO NOT EDIT MANUALLY - regenerated on every terraform apply
# =============================================================================

all:
  children:
    management:
      hosts:
        ${management_name}:
          ansible_host: ${management_ip}
          private_ip: ${management_private_ip}
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3

    application_servers:
      hosts:
%{ for node in vpc_nodes ~}
%{ if node.name != management_name ~}
        ${node.name}:
          ansible_host: ${node.ipv4_address}
          private_ip: ${node.ipv4_address_private}
          ansible_user: root
          ansible_python_interpreter: /usr/bin/python3
%{ endif ~}
%{ endfor ~}

  vars:
    management_host: ${management_name}
    prometheus_server: ${management_private_ip}
    loki_server: ${management_private_ip}
