---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: Reload systemd

- name: Restart promtail
  ansible.builtin.systemd:
    name: promtail
    state: restarted
  listen: Restart promtail
